"""Modal SFT launcher for CyberSecurity_OWASP action JSON data.

This trains a LoRA adapter on chat JSONL generated by
``scripts/generate_sft_dataset.py``.  It intentionally mirrors the repo's Modal
training pattern: local execution only launches remote jobs, while training runs
inside Modal and saves adapters to the persistent run volume.
"""

from __future__ import annotations

import json
import os
import pathlib
import subprocess
from datetime import datetime, timezone
from typing import Any

import modal


APP_NAME = "CyberSecurity_OWASP-sft"
VOLUME_NAME = "CyberSecurity_OWASP-grpo-runs"
CACHE_VOLUME_NAME = "CyberSecurity_OWASP-model-cache"
SECRET_NAME = "CyberSecurity_OWASP-secrets"
RUNS_DIR = pathlib.Path("/runs")
CACHE_DIR = pathlib.Path("/cache")
HF_HOME_DIR = CACHE_DIR / "huggingface"
HF_HUB_CACHE_DIR = HF_HOME_DIR / "hub"
TORCH_HOME_DIR = CACHE_DIR / "torch"
XDG_CACHE_DIR = CACHE_DIR / "xdg"
UNSLOTH_CACHE_DIR = CACHE_DIR / "unsloth"
TRITON_CACHE_DIR = CACHE_DIR / "triton"
REMOTE_PROJECT = "/root/CyberSecurity_OWASP"
PROJECT_ROOT = pathlib.Path(__file__).resolve().parents[1]
DEFAULT_GEMMA_MODEL = "unsloth/gemma-4-E2B-it"
PUBLIC_REPO_URL = "https://github.com/humandotlearning/CyberSecurity_OWASP.git"
PUBLIC_REPO_BRANCH = "master"


def _ensure_gemma4_model(model_name: str) -> str:
    if model_name != DEFAULT_GEMMA_MODEL:
        raise ValueError(
            "CyberSecurity_OWASP SFT is pinned to "
            f"{DEFAULT_GEMMA_MODEL}; received {model_name!r}."
        )
    return model_name


def _model_repo_slug(model_name: str) -> str:
    return model_name.replace("/", "-").replace("_", "-").replace(".", "-").lower()


def _configure_modal_cache_env() -> dict[str, str]:
    values = {
        "HF_HOME": str(HF_HOME_DIR),
        "HF_HUB_CACHE": str(HF_HUB_CACHE_DIR),
        "TRANSFORMERS_CACHE": str(HF_HUB_CACHE_DIR),
        "TORCH_HOME": str(TORCH_HOME_DIR),
        "XDG_CACHE_HOME": str(XDG_CACHE_DIR),
        "UNSLOTH_CACHE_DIR": str(UNSLOTH_CACHE_DIR),
        "UNSLOTH_COMPILE_CACHE": str(UNSLOTH_CACHE_DIR / "compile"),
        "TRITON_CACHE_DIR": str(TRITON_CACHE_DIR),
    }
    for key, value in values.items():
        os.environ[key] = value
    for path in {
        CACHE_DIR,
        HF_HOME_DIR,
        HF_HUB_CACHE_DIR,
        TORCH_HOME_DIR,
        XDG_CACHE_DIR,
        UNSLOTH_CACHE_DIR,
        UNSLOTH_CACHE_DIR / "compile",
        TRITON_CACHE_DIR,
    }:
        path.mkdir(parents=True, exist_ok=True)
    return values


def _cli_arg_value(name: str, default: str = "") -> str:
    import sys

    args = sys.argv[1:]
    flag = f"--{name}"
    for index, arg in enumerate(args):
        if arg == flag and index + 1 < len(args):
            return args[index + 1]
        if arg.startswith(f"{flag}="):
            return arg.split("=", 1)[1]
    return default


def _source_mode() -> str:
    return _cli_arg_value("source-mode", os.environ.get("MODAL_SOURCE_MODE", "local"))


def _training_image() -> modal.Image:
    image = (
        modal.Image.from_registry(
            "nvidia/cuda:12.8.0-devel-ubuntu22.04",
            add_python="3.11",
        )
        .apt_install("git", "build-essential", "curl")
        .uv_pip_install(
            "torch==2.10.0",
            "triton>=3.4.0",
            "torchvision==0.25.0",
            "bitsandbytes",
            "accelerate",
            "datasets",
            "huggingface_hub",
            "peft",
            "tokenizers",
            "trackio>=0.25.0",
            "transformers>=5.5.0",
            "trl>=0.28.0",
        )
        .uv_pip_install(
            "unsloth_zoo[base] @ git+https://github.com/unslothai/unsloth-zoo",
            "unsloth[base] @ git+https://github.com/unslothai/unsloth",
        )
        .uv_pip_install("timm", extra_options="--no-deps")
        .uv_pip_install("pydantic==2.10.6")
    )
    if _source_mode() == "public":
        repo_url = _cli_arg_value("repo-url", PUBLIC_REPO_URL)
        repo_branch = _cli_arg_value("repo-branch", PUBLIC_REPO_BRANCH)
        image = image.run_commands(
            f"git clone --depth 1 --branch {repo_branch} {repo_url} {REMOTE_PROJECT}",
            f"python -m pip install --no-deps -e {REMOTE_PROJECT}",
        )
    else:
        image = image.add_local_dir(
            PROJECT_ROOT,
            remote_path=REMOTE_PROJECT,
            copy=True,
            ignore=[
                ".git",
                ".venv",
                ".env",
                ".env.*",
                "__pycache__",
                ".pytest_cache",
                "outputs",
                "*.pyc",
            ],
        )
        image = image.run_commands(f"python -m pip install --no-deps -e {REMOTE_PROJECT}")
    return image.workdir(REMOTE_PROJECT)


app = modal.App(APP_NAME)
volume = modal.Volume.from_name(VOLUME_NAME, create_if_missing=True)
cache_volume = modal.Volume.from_name(CACHE_VOLUME_NAME, create_if_missing=True)
training_image = _training_image()
secrets = [modal.Secret.from_name(SECRET_NAME, required_keys=["HF_TOKEN"])]


@app.function(
    image=modal.Image.debian_slim(python_version="3.11"),
    timeout=60 * 20,
    volumes={RUNS_DIR: volume},
)
def upload_sft_jsonl(relative_path: str, content: str) -> str:
    target = RUNS_DIR / relative_path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    volume.commit()
    return str(target)


@app.function(
    image=training_image,
    gpu="L4",
    timeout=12 * 60 * 60,
    volumes={RUNS_DIR: volume, CACHE_DIR: cache_volume},
    secrets=secrets,
)
def train_cybersecurity_owasp_sft(
    train_jsonl: str = "/runs/sft/train.jsonl",
    validation_jsonl: str = "/runs/sft/validation.jsonl",
    output_repo_id: str = "",
    model_name: str = DEFAULT_GEMMA_MODEL,
    run_name: str = "",
    max_seq_length: int = 4096,
    max_steps: int = 100,
    num_train_epochs: float = 1.0,
    per_device_train_batch_size: int = 1,
    gradient_accumulation_steps: int = 16,
    learning_rate: float = 2e-5,
    lora_rank: int = 32,
    trackio_space_id: str = "Humanlearning/CyberSecurity_OWASP-trackio",
    trackio_project: str = "CyberSecurity_OWASP-sft",
    push_to_hub: bool = False,
) -> dict[str, Any]:
    import inspect

    from datasets import load_dataset
    from huggingface_hub import snapshot_download, whoami
    from trl import SFTConfig, SFTTrainer
    from trl.chat_template_utils import add_response_schema
    from unsloth import FastVisionModel

    model_name = _ensure_gemma4_model(model_name)
    cache_env = _configure_modal_cache_env()
    hf_token = os.environ.get("HF_TOKEN")
    if not hf_token:
        raise RuntimeError(f"HF_TOKEN is missing from the Modal secret {SECRET_NAME}.")

    user = whoami(token=hf_token)["name"]
    output_repo_id = output_repo_id or (
        f"{user}/CyberSecurity_OWASP-{_model_repo_slug(model_name)}-sft-lora"
    )
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    run_name = run_name or f"CyberSecurity_OWASP-{_model_repo_slug(model_name)}-sft-{stamp}"
    output_dir = RUNS_DIR / run_name
    adapter_dir = output_dir / "sft_adapter"
    output_dir.mkdir(parents=True, exist_ok=True)

    data_files = {"train": train_jsonl}
    validation_path = pathlib.Path(validation_jsonl)
    has_validation = validation_path.exists() and validation_path.stat().st_size > 0
    if has_validation:
        data_files["validation"] = validation_jsonl
    dataset = load_dataset("json", data_files=data_files)

    print(f"SFT run name: {run_name}")
    print(f"Model: {model_name}")
    print(f"Train JSONL: {train_jsonl}")
    print(f"Validation JSONL: {validation_jsonl if has_validation else '(none)'}")
    print(f"Output adapter dir: {adapter_dir}")
    print(f"Output repo: https://huggingface.co/{output_repo_id}")
    print(f"Trackio Space: https://huggingface.co/spaces/{trackio_space_id}")
    print(f"HF_HUB_CACHE: {cache_env['HF_HUB_CACHE']}")

    try:
        snapshot_download(repo_id=model_name, cache_dir=str(HF_HUB_CACHE_DIR), token=hf_token)
        cache_volume.commit()
    except Exception as exc:
        print(f"Model snapshot prefetch skipped; loader will retry directly. Error: {exc!r}")

    model_api = FastVisionModel
    model, tokenizer = model_api.from_pretrained(
        model_name=model_name,
        max_seq_length=max_seq_length,
        load_in_4bit=False,
        fast_inference=False,
        cache_dir=str(HF_HUB_CACHE_DIR),
        token=hf_token,
    )
    try:
        tokenizer = add_response_schema(tokenizer)
    except Exception as exc:
        print(f"Tokenizer response schema add skipped: {exc!r}")

    model = model_api.get_peft_model(
        model,
        r=lora_rank,
        target_modules=[
            "q_proj",
            "k_proj",
            "v_proj",
            "o_proj",
            "gate_proj",
            "up_proj",
            "down_proj",
        ],
        lora_alpha=lora_rank * 2,
        use_gradient_checkpointing="unsloth",
        random_state=3407,
    )
    if hasattr(model_api, "for_training"):
        model_api.for_training(model)

    sft_values = {
        "output_dir": str(output_dir),
        "max_seq_length": max_seq_length,
        "max_steps": max_steps,
        "num_train_epochs": num_train_epochs,
        "per_device_train_batch_size": per_device_train_batch_size,
        "gradient_accumulation_steps": gradient_accumulation_steps,
        "learning_rate": learning_rate,
        "logging_steps": 1,
        "save_steps": max(10, max_steps),
        "report_to": "trackio",
        "project": trackio_project,
        "trackio_space_id": trackio_space_id,
        "run_name": run_name,
        "assistant_only_loss": True,
        "packing": False,
        "gradient_checkpointing": True,
        "gradient_checkpointing_kwargs": {"use_reentrant": False},
        "push_to_hub": push_to_hub,
        "hub_model_id": output_repo_id,
        "hub_private_repo": True,
    }
    sft_parameters = set(inspect.signature(SFTConfig).parameters)
    skipped = sorted(set(sft_values) - sft_parameters)
    if skipped:
        print(f"Skipping unsupported SFTConfig keys: {skipped}")
    training_args = SFTConfig(
        **{key: value for key, value in sft_values.items() if key in sft_parameters}
    )

    trainer_values = {
        "model": model,
        "processing_class": tokenizer,
        "args": training_args,
        "train_dataset": dataset["train"],
        "eval_dataset": dataset["validation"] if has_validation else None,
    }
    trainer_parameters = set(inspect.signature(SFTTrainer).parameters)
    skipped_trainer = sorted(
        key for key, value in trainer_values.items() if key not in trainer_parameters and value is not None
    )
    if skipped_trainer:
        print(f"Skipping unsupported SFTTrainer keys: {skipped_trainer}")
    trainer = SFTTrainer(
        **{
            key: value
            for key, value in trainer_values.items()
            if value is not None and key in trainer_parameters
        }
    )
    trainer.train()
    trainer.save_model(str(adapter_dir))
    if push_to_hub:
        trainer.push_to_hub()
    volume.commit()
    cache_volume.commit()
    return {
        "run_name": run_name,
        "model_name": model_name,
        "adapter_dir": str(adapter_dir),
        "output_repo_id": output_repo_id,
        "train_jsonl": train_jsonl,
        "validation_jsonl": validation_jsonl if has_validation else "",
        "max_steps": max_steps,
        "push_to_hub": push_to_hub,
        "trackio_space_id": trackio_space_id,
        "trackio_project": trackio_project,
    }


def _git_sha(default: str = "nogit") -> str:
    try:
        return subprocess.check_output(
            [
                "git",
                "-c",
                f"safe.directory={PROJECT_ROOT.as_posix()}",
                "rev-parse",
                "HEAD",
            ],
            cwd=PROJECT_ROOT,
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except Exception:
        return default


@app.local_entrypoint()
def main(
    mode: str = "train",
    local_train_path: str = "outputs/sft/train.jsonl",
    local_validation_path: str = "outputs/sft/validation.jsonl",
    train_jsonl: str = "/runs/sft/train.jsonl",
    validation_jsonl: str = "/runs/sft/validation.jsonl",
    output_repo_id: str = "",
    model_name: str = DEFAULT_GEMMA_MODEL,
    run_name: str = "",
    max_seq_length: int = 4096,
    max_steps: int = 100,
    num_train_epochs: float = 1.0,
    per_device_train_batch_size: int = 1,
    gradient_accumulation_steps: int = 16,
    learning_rate: float = 2e-5,
    lora_rank: int = 32,
    trackio_space_id: str = "Humanlearning/CyberSecurity_OWASP-trackio",
    trackio_project: str = "CyberSecurity_OWASP-sft",
    source_mode: str = "local",
    repo_url: str = PUBLIC_REPO_URL,
    repo_branch: str = PUBLIC_REPO_BRANCH,
    detach: bool = False,
    push_to_hub: bool = False,
) -> None:
    del source_mode, repo_url, repo_branch  # consumed during image construction
    model_name = _ensure_gemma4_model(model_name)
    if mode not in {"upload", "train"}:
        raise ValueError("mode must be 'upload' or 'train'")

    local_train = pathlib.Path(local_train_path)
    local_validation = pathlib.Path(local_validation_path)
    if local_train.exists():
        uploaded = upload_sft_jsonl.remote(
            "sft/train.jsonl",
            local_train.read_text(encoding="utf-8"),
        )
        print(f"Uploaded train JSONL: {uploaded}")
        train_jsonl = uploaded
    if local_validation.exists():
        uploaded_validation = upload_sft_jsonl.remote(
            "sft/validation.jsonl",
            local_validation.read_text(encoding="utf-8"),
        )
        print(f"Uploaded validation JSONL: {uploaded_validation}")
        validation_jsonl = uploaded_validation
    if mode == "upload":
        return

    if not run_name:
        stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
        run_name = f"CyberSecurity_OWASP-{_model_repo_slug(model_name)}-sft-{stamp}-{_git_sha()[:8]}"

    kwargs = dict(
        train_jsonl=train_jsonl,
        validation_jsonl=validation_jsonl,
        output_repo_id=output_repo_id,
        model_name=model_name,
        run_name=run_name,
        max_seq_length=max_seq_length,
        max_steps=max_steps,
        num_train_epochs=num_train_epochs,
        per_device_train_batch_size=per_device_train_batch_size,
        gradient_accumulation_steps=gradient_accumulation_steps,
        learning_rate=learning_rate,
        lora_rank=lora_rank,
        trackio_space_id=trackio_space_id,
        trackio_project=trackio_project,
        push_to_hub=push_to_hub,
    )
    print(f"SFT run name: {run_name}")
    print(f"Train JSONL: {train_jsonl}")
    print(f"Validation JSONL: {validation_jsonl}")
    print(f"Hub push enabled: {push_to_hub}")
    if detach:
        call = train_cybersecurity_owasp_sft.spawn(**kwargs)
        print(f"Spawned Modal SFT call: {call.object_id}")
    else:
        result = train_cybersecurity_owasp_sft.remote(**kwargs)
        print(json.dumps(result, indent=2, sort_keys=True))
